# Generated by Django 2.0.1 on 2018-03-23 03:48

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', core.models.GeneralCharField(max_length=191)),
                ('cron', core.models.GeneralCharField(blank=True, max_length=191, null=True)),
                ('rate_offer', models.PositiveSmallIntegerField(default=0)),
                ('virtual_click', models.PositiveSmallIntegerField(default=0)),
                ('virtual_lead', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'networks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', core.models.GeneralCharField(max_length=191)),
                ('redirect_link', core.models.GeneralCharField(blank=True, max_length=191, null=True)),
                ('click_rate', models.FloatField(null=True)),
                ('geo_locations', core.models.GeneralCharField(blank=True, max_length=191, null=True)),
                ('allow_devices', models.PositiveSmallIntegerField(default=0)),
                ('net_offer_id', models.PositiveIntegerField(null=True)),
                ('image', core.models.GeneralCharField(blank=True, max_length=191, null=True)),
                ('status', models.BooleanField(default=True)),
                ('auto', models.BooleanField(default=False)),
                ('allow_multi_lead', models.BooleanField(default=False)),
                ('check_click_in_network', models.BooleanField(default=False)),
                ('number_when_click', models.PositiveSmallIntegerField(default=0)),
                ('number_when_lead', models.PositiveSmallIntegerField(default=0)),
                ('test_link', core.models.GeneralCharField(blank=True, max_length=191, null=True)),
                ('reject', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'offers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CronLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', core.models.GeneralCharField(max_length=191)),
                ('network_name', core.models.GeneralCharField(max_length=191)),
                ('network_id', models.PositiveIntegerField()),
                ('log', models.TextField()),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
